  CREATE TABLE "AUCTION" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"PRODUCT_ID" NUMBER, 
	"STARTDATE" TIMESTAMP (6), 
	"ENDDATE" TIMESTAMP (6), 
	"OWNER" VARCHAR2(50 BYTE), 
	"MINIMUM_BID" NUMBER, 
	 CONSTRAINT "AUCTION_PK" PRIMARY KEY ("ID") ) ;
	 

  CREATE TABLE "BID" 
   (	"ID" NUMBER NOT NULL ENABLE, 
	"AMOUNT" NUMBER, 
	"EMAIL" VARCHAR2(20 BYTE), 
	"CREATED" TIMESTAMP (6), 
	"AUCTION_ID" NUMBER, 
	 CONSTRAINT "BID_PK" PRIMARY KEY ("ID") );

CREATE TABLE "PRODUCT" 
   ("ID" NUMBER NOT NULL ENABLE, 
	"TITLE" VARCHAR2(50 BYTE), 
	"DESCRIPTION" CLOB, 
	 CONSTRAINT "PRODUCT_PK" PRIMARY KEY ("ID")  ); 
	 